# Configuration du document PagedJS
# Généré automatiquement depuis l'onglet Configurations

# === INFORMATIONS GÉNÉRALES ===
theme: "theme/valentine"
title: "Désencombrement"
subtitle: "Index d’une société à venir, allégée de ses objets"
runningtitle: ""

# === AUTEUR ET CONTEXTE ===
name: "VALENTINE SAINT-MARTIN"
mention: "Mémoire de Diplôme National Supérieur d'Expression Plastique"
option: "option Design"
year: "2024 – 2025"
directeur: "sous la direction de Jean Charles Zebo"
ecole: "ebabx – école supérieure des beaux-arts de Bordeaux"

# === FICHIER PDF ===
pdf: ""

# === DOSSIER À SERVIR ===
publicFolder: "memoire-Valentine"


# Structure du contenu (= sommaire)
parts:
  - title: "Cover"
    file : content/text/00.cover.md

  - title: "Introduction"
    file: content/text/10.introduction.md

  - title: "Introduction-text"
    file: content/text/11.introduction-text.md

  - title: "Domestique"
    file: content/text/20.domestique-titre.md

  - title: "Domestique-text"
    file: content/text/21.domestique-texte.md